### PR TITLE
update package version

### PR DESCRIPTION
**Pull request by fpkamp**
@Finesse if everything is good with [the other PR](https://github.com/fingerprintjs/broyster/pull/44), can you please merge that one and this one and release before you get on your flight?

### CODE REVIEW

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Review by Finesse — APPROVED** [review]
Merge when all the needed PRs are merged

**Comment by fpkamp** [comment]
Should we wait for [this PR](https://github.com/fingerprintjs/broyster/pull/47)?

**Comment by Finesse** [comment]
> Should we wait for [this PR](https://github.com/fingerprintjs/broyster/pull/47)?

No, we can publish the change later the same day

**Comment by Finesse** [comment]
@fpkamp Published

**Pull request merged**
